import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { CartProvider} from "../app/context/CartContext"
import "./globals.css";
import Navbar from "./compunents/Navbar";
import Footer from "./compunents/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
      <CartProvider>{children} </CartProvider>
      <Footer/>
      </body>
    </html>
  );
}
